# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
#-4614
speed_to_erpm_gain: -29000
speed_to_erpm_offset: 0.0

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit

max_servo_speed: 1.34 # radians/secon #original
#max_servo_speed: 1.0 


servo_smoother_rate: 75.0 
# messages/sec

# servo smoother - limits acceleration and smooths anything above limit
#max_acceleration: 2.5 (default)
max_acceleration: 15
# meters/second^2
throttle_smoother_rate: 75.0 
# messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: 1.5
steering_angle_to_servo_offset: 0.432

# publish odom to base link tf
vesc_to_odom/publish_tf: false

# car wheelbase is about 25cm 
chassis_length: 0.3 
wheelbase: .48

vesc_driver:
  port: /dev/vesc
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 20.0
  brake_min: -20000.0
  brake_max: 200000.0
  speed_min: -10000
  speed_max: 10000
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.0
  servo_max: 1.0
  invert_servo: false
